# Generated by Django 4.1.7 on 2023-05-18 13:45

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_route_static', '0002_netboxmodel_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticroute',
            options={'ordering': ['vrf', 'prefix', 'metric']},
        ),
        migrations.AddConstraint(
            model_name='staticroute',
            constraint=models.UniqueConstraint(models.F('vrf'), models.F('prefix'), models.F('next_hop'), name='netbox_route_static_staticroute_unique_vrf_prefix_nexthop', violation_error_message='VRF, Prefix and Next Hop must be unique.'),
        ),
    ]
